import { Command } from 'commander';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs-extra';
import { scanRepo } from '../../advisor/repoScan.js';
import { mineHistory } from '../../advisor/historyMiner.js';
import { suggestRules, generateSuggestionsWithML } from '../../advisor/suggest.js';
import type { RuleSuggestion } from '../../advisor/types.js';
import type { Rule } from '../../types/index.js';

const SEVERITY_COLOR: Record<string, (s: string) => string> = {
  high: chalk.red,
  medium: chalk.yellow,
  low: chalk.cyan,
};

function formatSuggestion(s: RuleSuggestion, index: number): void {
  const color = SEVERITY_COLOR[s.severity] ?? chalk.white;
  console.log(color(`  ${index + 1}. [${s.severity.toUpperCase()}] ${s.category}`));
  console.log(`     ${chalk.bold(s.text)}`);
  console.log(`     ${chalk.gray(s.reason)}`);
  console.log('');
}

function generateMarkdown(suggestions: RuleSuggestion[], targetDir: string): string {
  const lines: string[] = [
    '# RuleProbe Rule Advisor Suggestions',
    '',
    `Target: \`${targetDir}\``,
    `Generated: ${new Date().toISOString()}`,
    '',
  ];

  if (suggestions.length === 0) {
    lines.push('No gaps detected. Your rule coverage looks good!');
    return lines.join('\n');
  }

  lines.push(`Found **${suggestions.length}** suggestion(s):`);
  lines.push('');

  for (const s of suggestions) {
    lines.push(`## [${s.severity.toUpperCase()}] \`${s.category}\``);
    lines.push('');
    lines.push(`**Suggested rule:** ${s.text}`);
    lines.push('');
    lines.push(`**Reason:** ${s.reason}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by RuleProbe — suggestions are proposals only, never auto-applied.*');
  return lines.join('\n');
}

/**
 * Read existing rules from .ruleprobe/report.json if it exists.
 * Returns empty array if missing or malformed.
 */
async function readExistingRules(reportDir: string): Promise<Rule[]> {
  const reportPath = path.join(reportDir, 'report.json');
  if (!(await fs.pathExists(reportPath))) return [];

  try {
    const report = await fs.readJson(reportPath);
    // report.json stores results, not raw rules — extract from results
    const results: Array<{ scenario?: { ruleId?: string; ruleCategory?: string; ruleText?: string }; category?: string; ruleText?: string; ruleId?: string }> =
      Array.isArray(report.results) ? report.results : [];

    // Reconstruct a minimal Rule-like array from result entries (for gap detection)
    const seen = new Set<string>();
    const rules: Rule[] = [];
    for (const r of results) {
      const id = r.scenario?.ruleId ?? r.ruleId ?? '';
      if (!id || seen.has(id)) continue;
      seen.add(id);

      const category = (r.scenario?.ruleCategory ?? r.category ?? 'unknown') as Rule['category'];
      const text = r.scenario?.ruleText ?? r.ruleText ?? '';
      rules.push({
        id,
        sourceFile: '',
        text,
        category,
        severity: 'medium',
        testable: true,
        assertions: [],
      });
    }
    return rules;
  } catch {
    return [];
  }
}

export function register(program: Command): void {
  program
    .command('advise [dir]')
    .description('Analyze repo and suggest missing or conflicting rules')
    .option('--json', 'Output suggestions as JSON')
    .option('--ml', 'Use ML-powered semantic similarity (requires: pnpm add @xenova/transformers)')
    .option('--report-dir <dir>', 'Override .ruleprobe report directory')
    .action(async (dir: string | undefined, options: { json?: boolean; ml?: boolean; reportDir?: string }) => {
      const targetDir = path.resolve(dir ?? process.cwd());
      const reportDir = options.reportDir
        ? path.resolve(options.reportDir)
        : path.join(targetDir, '.ruleprobe');

      if (!options.json) {
        console.log(chalk.bold.cyan('\nRuleProbe Advisor'));
        console.log(chalk.gray(`  Scanning: ${targetDir}\n`));
      }

      // 1. Scan the repo
      const scan = await scanRepo(targetDir);

      // 2. Mine history
      const history = await mineHistory(reportDir);

      // 3. Read existing rules from previous report.json (if any)
      const existingRules = await readExistingRules(reportDir);

      // 4. Generate suggestions
      const suggestions = suggestRules(scan, history, existingRules);

      // 4b. ML-powered semantic duplicate/conflict detection
      if (options.ml && existingRules.length > 0) {
        if (!options.json) {
          console.log(chalk.cyan('  Running ML semantic analysis…'));
        }
        const mlSuggestions = await generateSuggestionsWithML(existingRules);
        for (const text of mlSuggestions) {
          suggestions.push({ category: 'required_command', text, severity: 'medium', reason: 'Detected via ML semantic similarity.' });
        }
      }

      // 5. Handle JSON output
      if (options.json) {
        console.log(JSON.stringify({ scan, history, suggestions }, null, 2));
        return;
      }

      // 6. Print scan summary
      console.log(chalk.bold('Repo Scan'));
      console.log(`  Package manager: ${scan.packageManager ?? chalk.gray('not detected')}`);
      console.log(`  Test runner:     ${scan.testRunner ?? chalk.gray('not detected')}`);
      console.log(`  Linters:         ${scan.linters.length > 0 ? scan.linters.join(', ') : chalk.gray('none detected')}`);
      if (scan.frequentDirs.length > 0) {
        console.log(`  Frequent dirs:   ${scan.frequentDirs.join(', ')}`);
      }

      console.log('');
      console.log(chalk.bold('History'));
      if (history.totalRuns === 0) {
        console.log(`  ${chalk.gray('No run history found')}`);
      } else {
        const trendArrow = history.trend === 'improving' ? chalk.green('↑') : history.trend === 'declining' ? chalk.red('↓') : chalk.gray('→');
        console.log(`  Runs: ${history.totalRuns}  |  Failure rate: ${history.failureRate}%  |  Trend: ${trendArrow} ${history.trend}`);
      }

      console.log('');

      // 7. Print suggestions
      if (suggestions.length === 0) {
        console.log(chalk.green('No gaps detected. Your rule coverage looks good!'));
      } else {
        console.log(chalk.bold(`Suggestions (${suggestions.length}):`));
        console.log('');
        suggestions.forEach((s, i) => formatSuggestion(s, i));
      }

      // 8. Write output files
      await fs.ensureDir(reportDir);

      const suggestionsJsonPath = path.join(reportDir, 'suggestions.json');
      await fs.writeFile(
        suggestionsJsonPath,
        JSON.stringify({ scan, history, suggestions }, null, 2),
        'utf-8'
      );

      const suggestionsMdPath = path.join(reportDir, 'suggestions.md');
      await fs.writeFile(suggestionsMdPath, generateMarkdown(suggestions, targetDir), 'utf-8');

      console.log(chalk.gray(`\nSuggestions written to:`));
      console.log(chalk.gray(`  ${suggestionsJsonPath}`));
      console.log(chalk.gray(`  ${suggestionsMdPath}`));
    });
}
