import { Command } from 'commander';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs-extra';
import jsYaml from 'js-yaml';

const CI_WORKFLOW_GITHUB = `name: RuleProbe Compliance

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ruleprobe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run RuleProbe
        run: npx ruleprobe-ai@latest run . --provider mock --fail-below 70
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ruleprobe-report
          path: .ruleprobe/report.md
          if-no-files-found: ignore
`;

const CI_WORKFLOW_GITLAB = `ruleprobe:
  stage: test
  image: node:20
  script:
    - npx ruleprobe-ai@latest run . --provider mock --fail-below 70
  artifacts:
    when: always
    paths:
      - .ruleprobe/report.md
    expire_in: 7 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`;

export interface SeedRule {
  text: string;
  category: string;
  severity: 'low' | 'medium' | 'high';
}

/** Minimal interface for the clack prompts subset we use. */
export interface ClackAdapter {
  intro: (msg: string) => void;
  outro: (msg: string) => void;
  confirm: (opts: { message: string; initialValue?: boolean }) => Promise<boolean | symbol>;
  isCancel: (val: unknown) => val is symbol;
  cancel: (msg: string) => void;
}

export function buildSeedYaml(rules: SeedRule[]): string {
  const doc = {
    rules: rules.map(r => ({ text: r.text, category: r.category, severity: r.severity })),
  };
  return (
    '# Generated by ruleprobe init --interactive\n' +
    '# Review and copy rules to your instruction files (CLAUDE.md, AGENTS.md, etc.)\n' +
    jsYaml.dump(doc, { lineWidth: 120 })
  );
}

/** Core wizard logic — accepts clack and scanRepo as injectables for testability. */
export async function runInitWizard(
  targetDir: string,
  clack: ClackAdapter,
  scanRepo: (dir: string) => Promise<{
    packageManager: string | null;
    testRunner: string | null;
    linters: string[];
    frequentDirs: string[];
    hasLockfile: boolean;
  }>
): Promise<SeedRule[]> {
  clack.intro(chalk.bold.cyan('RuleProbe Init Wizard'));

  const scan = await scanRepo(targetDir);
  const rules: SeedRule[] = [];

  // Package manager question — only if detected
  if (scan.packageManager) {
    const usePm = await clack.confirm({
      message: `Use ${scan.packageManager} as package manager?`,
      initialValue: true,
    });

    if (clack.isCancel(usePm)) {
      clack.cancel('Wizard cancelled.');
      process.exit(0);
    }

    if (usePm === true) {
      rules.push({
        text: `Always use ${scan.packageManager}`,
        category: 'package_manager',
        severity: 'high',
      });
    }
  }

  // Protect generated dirs question — always asked
  const protectDirs = await clack.confirm({
    message: 'Protect generated output dirs (dist/, build/, .next/)?',
    initialValue: true,
  });

  if (clack.isCancel(protectDirs)) {
    clack.cancel('Wizard cancelled.');
    process.exit(0);
  }

  if (protectDirs === true) {
    for (const dir of ['dist/', 'build/', '.next/']) {
      rules.push({
        text: `Do not modify files in ${dir}`,
        category: 'forbidden_file_change',
        severity: 'medium',
      });
    }
  }

  // Linter question — only if linters detected
  if (scan.linters.length > 0) {
    const linterList = scan.linters.join(', ');
    const enforceLinters = await clack.confirm({
      message: `Enforce ${linterList} must run?`,
      initialValue: true,
    });

    if (clack.isCancel(enforceLinters)) {
      clack.cancel('Wizard cancelled.');
      process.exit(0);
    }

    if (enforceLinters === true) {
      for (const linter of scan.linters) {
        rules.push({
          text: `Run ${linter} before committing`,
          category: 'linter_must_run',
          severity: 'medium',
        });
      }
    }
  }

  // Test runner question — only if detected
  if (scan.testRunner) {
    const requireTests = await clack.confirm({
      message: `Require ${scan.testRunner} to be run?`,
      initialValue: true,
    });

    if (clack.isCancel(requireTests)) {
      clack.cancel('Wizard cancelled.');
      process.exit(0);
    }

    if (requireTests === true) {
      rules.push({
        text: `Run ${scan.testRunner} before pushing`,
        category: 'required_command',
        severity: 'high',
      });
    }
  }

  clack.outro(chalk.green('Config initialized!'));

  return rules;
}

export function register(program: Command): void {
  program
    .command('init [dir]')
    .description('Initialize ruleprobe config')
    .option('--from-claude', 'Auto-detect instruction files (CLAUDE.md, AGENTS.md, .cursor/rules, etc.) from the target directory')
    .option('--provider <name>', 'Default provider for the generated config (default: mock)', 'mock')
    .option('--with-ci', 'Generate a GitHub Actions workflow file in the target directory')
    .option('--ci <platform>', 'Generate CI config: github-actions (default) | gitlab')
    .option('--interactive', 'Run an interactive wizard to configure rules')
    .action(async (dir: string | undefined, options) => {
      const targetDir = dir ? path.resolve(dir) : process.cwd();
      const defaultPatterns = ["CLAUDE.md", "AGENTS.md", ".cursor/rules/*.mdc", ".github/copilot-instructions.md"];

      let instructionFiles = defaultPatterns;
      if (options.fromClaude) {
        const glob = await import('fast-glob');
        const found = await glob.default(defaultPatterns, { cwd: targetDir, ignore: ['node_modules/**'] });
        if (found.length > 0) {
          instructionFiles = found;
          console.log(chalk.green(`Detected ${found.length} instruction file(s): ${found.join(', ')}`));
        } else {
          console.log(chalk.yellow('No instruction files detected; using default patterns.'));
        }
      }

      const configPath = path.join(targetDir, 'ruleprobe.config.json');
      await fs.writeFile(configPath, JSON.stringify({
        provider: options.provider,
        instructionFiles,
        reportDir: ".ruleprobe",
        failBelow: 70,
        keepSandbox: false
      }, null, 2));
      console.log(chalk.green(`Initialized ${configPath} with minimal config`));

      const ciPlatform = options.ci ?? (options.withCi ? 'github-actions' : null);
      if (ciPlatform) {
        if (ciPlatform === 'gitlab') {
          const ciPath = path.join(targetDir, '.gitlab-ci.yml');
          const existing = (await fs.pathExists(ciPath)) ? await fs.readFile(ciPath, 'utf-8') : '';
          const block = existing ? `\n# --- RuleProbe Compliance ---\n${CI_WORKFLOW_GITLAB}` : CI_WORKFLOW_GITLAB;
          await fs.appendFile(ciPath, block, 'utf-8');
          console.log(chalk.green(`Created/updated ${ciPath}`));
          console.log(chalk.dim(`  Edit the job to set your preferred provider and fail-below threshold.`));
        } else {
          // github-actions (default)
          const workflowDir = path.join(targetDir, '.github', 'workflows');
          await fs.ensureDir(workflowDir);
          const workflowPath = path.join(workflowDir, 'ruleprobe-compliance.yml');
          await fs.writeFile(workflowPath, CI_WORKFLOW_GITHUB, 'utf-8');
          console.log(chalk.green(`Created ${workflowPath}`));
          console.log(chalk.dim(`  Edit the workflow to set your preferred provider and fail-below threshold.`));
        }
      }

      // Interactive wizard
      if (options.interactive) {
        const clackMod = await import('@clack/prompts');
        const { scanRepo } = await import('../../advisor/repoScan.js');

        const clackAdapter: ClackAdapter = {
          intro: clackMod.intro,
          outro: clackMod.outro,
          confirm: clackMod.confirm,
          isCancel: clackMod.isCancel,
          cancel: clackMod.cancel,
        };

        const seedRules = await runInitWizard(targetDir, clackAdapter, scanRepo);

        const rpDir = path.join(targetDir, '.ruleprobe');
        await fs.ensureDir(rpDir);
        const seedPath = path.join(rpDir, 'seed-rules.yaml');
        await fs.writeFile(seedPath, buildSeedYaml(seedRules), 'utf-8');
        console.log(chalk.green(`\nSeed rules written to: ${seedPath}`));
        console.log(chalk.dim('  Copy rules from seed-rules.yaml into your CLAUDE.md, AGENTS.md, etc.'));
      }

      if (!options.interactive) {
        console.log(chalk.dim(`\n  Next steps:`));
        console.log(chalk.dim(`  1. ruleprobe list-rules ${dir || '.'}`));
        console.log(chalk.dim(`  2. ruleprobe run ${dir || '.'} --provider mock`));
      }
    });
}
