import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import readline from 'readline';
import { loadConfig } from '../../config/load.js';
import { loadRuleHistory } from '../../history/ruleHistory.js';
import { detectStruggling } from '../../optimize/detect.js';
import { rewriteRule } from '../../optimize/rewrite.js';

export function register(program: Command): void {
  program
    .command('optimize [dir]')
    .description('Analyse run history to find chronically-failing rules and rewrite them for clarity')
    .option('--provider <provider>', 'AI provider for rewrites (anthropic, openai, gemini, openrouter). Falls back to deterministic if not set.')
    .option('--min-runs <n>', 'Minimum number of recorded runs before a rule is considered', '3')
    .option('--threshold <pct>', 'Fail-rate threshold (0–100) above which a rule is flagged', '40')
    .option('--write', 'Apply rewrites to source instruction files (requires confirmation per rule)')
    .option('--report-dir <dir>', 'Override report directory')
    .action(async (dir, options) => {
      if (dir) process.chdir(dir);

      const config = await loadConfig();
      if (options.reportDir) config.reportDir = options.reportDir;
      if (options.provider) config.provider = options.provider;

      const minRuns = parseInt(options.minRuns ?? '3', 10);
      const threshold = parseInt(options.threshold ?? '40', 10) / 100;

      const history = await loadRuleHistory(config);

      if (history.length === 0) {
        console.log(chalk.yellow(
          'No rule history found. Run `ruleprobe run` a few times first to build history.\n' +
          `Expected history file: ${path.join(config.reportDir, 'rule-history.json')}`
        ));
        return;
      }

      const struggling = detectStruggling(history, minRuns, threshold);

      if (struggling.length === 0) {
        console.log(chalk.green(
          `No chronically-failing rules found (threshold: ${Math.round(threshold * 100)}%, minRuns: ${minRuns}).`
        ));
        return;
      }

      console.log(chalk.bold.yellow(
        `\nFound ${struggling.length} chronically-failing rule(s) (≥${Math.round(threshold * 100)}% fail rate):\n`
      ));

      const rewrites: Array<{
        ruleText: string;
        before: string;
        after: string;
        rationale: string;
        failRate: number;
        runs: number;
        sourceFile?: string;
        sourceLine?: number;
      }> = [];

      for (const s of struggling) {
        const failPct = Math.round(s.failRate * 100);
        console.log(chalk.red(`  [${failPct}% fail / ${s.runs} runs] ${s.history.ruleText}`));
        if (s.history.sourceFile) {
          console.log(chalk.dim(`    Source: ${s.history.sourceFile}:${s.history.sourceLine ?? '?'}`));
        }

        process.stdout.write(chalk.dim('  Rewriting... '));
        const rw = await rewriteRule(s.history, config);
        console.log(chalk.dim('done'));

        rewrites.push({
          ruleText: s.history.ruleText,
          before: rw.before,
          after: rw.after,
          rationale: rw.rationale,
          failRate: s.failRate,
          runs: s.runs,
          sourceFile: s.history.sourceFile,
          sourceLine: s.history.sourceLine,
        });
      }

      // Write proposal files
      const mdLines: string[] = [
        '# RuleProbe Optimize — Proposed Rule Rewrites',
        `\n_Generated: ${new Date().toISOString()}_`,
        `_Threshold: ≥${Math.round(threshold * 100)}% fail rate over ≥${minRuns} runs_\n`,
        '---\n',
      ];

      for (const rw of rewrites) {
        const failPct = Math.round(rw.failRate * 100);
        mdLines.push(`## Rule: \`${rw.ruleText.slice(0, 80)}\``);
        mdLines.push(`\n**Stats:** ${failPct}% fail rate over ${rw.runs} run(s)`);
        if (rw.sourceFile) mdLines.push(`**Source:** \`${rw.sourceFile}:${rw.sourceLine ?? '?'}\``);
        mdLines.push('\n**Before:**');
        mdLines.push('```');
        mdLines.push(rw.before);
        mdLines.push('```');
        mdLines.push('\n**After (proposed):**');
        mdLines.push('```');
        mdLines.push(rw.after);
        mdLines.push('```');
        mdLines.push(`\n**Rationale:** ${rw.rationale}\n`);
        mdLines.push('---\n');
      }
      mdLines.push('_Generated by RuleProbe — suggestions are proposals only unless --write was used._');

      await fs.ensureDir(config.reportDir);
      const mdPath = path.join(config.reportDir, 'optimized.md');
      const jsonPath = path.join(config.reportDir, 'optimized.json');

      await fs.writeFile(mdPath, mdLines.join('\n'), 'utf-8');
      await fs.writeJson(jsonPath, rewrites, { spaces: 2 });

      console.log(chalk.green(`\nProposals written to:\n  ${mdPath}\n  ${jsonPath}`));

      if (!options.write) {
        console.log(chalk.dim('\nTip: Run with --write to apply rewrites to source files after confirmation.'));
        return;
      }

      // --write mode: apply with per-rule confirmation
      console.log(chalk.bold.yellow('\n⚠  --write mode: each rewrite will be applied after your confirmation.\n'));

      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      const ask = (q: string): Promise<string> =>
        new Promise(resolve => rl.question(q, resolve));

      let applied = 0;
      let skipped = 0;

      for (const rw of rewrites) {
        if (!rw.sourceFile || rw.sourceLine == null) {
          console.log(chalk.dim(`  Skipping "${rw.ruleText.slice(0, 60)}" — no source location recorded.`));
          skipped++;
          continue;
        }

        console.log(chalk.bold(`\nRule: ${rw.ruleText.slice(0, 80)}`));
        console.log(chalk.red(`  Before: ${rw.before}`));
        console.log(chalk.green(`  After:  ${rw.after}`));
        console.log(chalk.dim(`  Source: ${rw.sourceFile}:${rw.sourceLine}`));

        const answer = await ask(chalk.yellow('  Apply this rewrite? [y/N] '));

        if (answer.trim().toLowerCase() !== 'y') {
          console.log(chalk.dim('  Skipped.'));
          skipped++;
          continue;
        }

        try {
          const filePath = path.resolve(rw.sourceFile);
          const content = await fs.readFile(filePath, 'utf-8');
          const lines = content.split('\n');
          const lineIdx = rw.sourceLine - 1;

          if (lineIdx >= 0 && lineIdx < lines.length) {
            // Replace the line — preserve leading list marker if present
            const original = lines[lineIdx];
            const listPrefix = original.match(/^(\s*[-*]\s*)/)?.[1] ?? '';
            lines[lineIdx] = listPrefix + rw.after;
            await fs.writeFile(filePath, lines.join('\n'), 'utf-8');
            console.log(chalk.green(`  ✓ Applied to ${rw.sourceFile}:${rw.sourceLine}`));
            applied++;
          } else {
            console.log(chalk.red(`  Line ${rw.sourceLine} out of range in ${rw.sourceFile}.`));
            skipped++;
          }
        } catch (e: any) {
          console.log(chalk.red(`  Error applying rewrite: ${e.message}`));
          skipped++;
        }
      }

      rl.close();
      console.log(chalk.bold(`\nOptimize complete: ${applied} applied, ${skipped} skipped.`));
    });
}
